---
title: "Scouting for Phone Pervasiveness"
author: "Fluve Vandelli"
date: "`r Sys.Date()`"
output: html_document
---

## Data Exploration
```{r}
setwd("~/Desktop/Social Dynamics Lab")

library(lubridate)
library(ggplot2)
library(dplyr)
library(haven)
data4diarynew_ITA <- read_dta("Processed Data/data4diarynew_ITA.dta")
td_ita <- read_dta("Processed Data/td_ita.dta")
touch_sensor_Fluve <- read.csv("~/Desktop/Social Dynamics Lab/Processed Data/touch_sensor_Fluve.csv")
touch_sensor_Mattia <- read.csv("~/Desktop/Social Dynamics Lab/Processed Data/touch_sensor_Mattia.csv")
```

```{r Summary for touch sensor}
summary(touch_sensor_Fluve$touches)
line(touch_sensor_Fluve$touches)
```

```{r}
summary(touch_sensor_Mattia$event_count)
hist(touch_sensor_Mattia$event_count)
```


```{r}
nrow(touch_sensor_Fluve)  # 1248328
nrow(touch_sensor_Mattia) # 1237536
```
```{r}
View(touch_sensor_Fluve)
```
I want to see how much user 3 was touching November 27.
```{r}
# Load necessary packages
library(ggplot2)
library(lubridate)
library(nycflights13)

df <- read.csv("Processed Data/grouped_hourly.csv")

# conversion from timestamp to time vector + setting start circadian day
start_datetime <- ymd_hms("2023-11-27 05:00:00")
end_datetime <- ymd_hms("2023-11-28 04:30:00")

day <- df %>%
  filter(timestamp >= start_datetime, timestamp <= end_datetime)
```




